---
title: "ChallengeQuestionsLession5_XinHuang"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

rm(list=ls())

library("plyr")
library("dplyr")
library("tidyr")
library("lattice")
library("ggplot2")
library("tibble")
library("graphics")
```

#Challenge Question 1
```{r echo = TRUE, fig=TRUE, fig.align='center'}
pchMy <- c("22","23","24","25","8")
colorMy <- c("midnightblue","#00FF00", "#FF0000","4","yellow")
dfMy <- data.frame(
    xMy = c(1,3,5,7,9),
    yMy = c(1,3,5,7,9),
    colorMy = c("midnightblue","#00FF00", "#FF0000","4","yellow")
)

#manipulating size 
mySize <- c(3, 1, 1, 1, 1)
qplot(xMy, yMy, data = dfMy,
      col = colorMy,
      pch = pchMy,
      size = mySize,
      main ="Using pchand col from Base Package (point size changed)")

# lable points
# use row names as lables
ggplot(dfMy, aes(xMy, yMy)) + 
    geom_point(aes(color = colorMy), shape = 19, alpha = 0.5) +
    geom_text(aes(label = rownames(dfMy)), position = "identity", size = 5, vjust = -2)

# change legends title
ggplot(dfMy, aes(xMy, yMy)) + 
    geom_point(aes(color = colorMy), shape = 19, alpha = 0.5) + 
    guides(color=guide_legend(title="New Legend Title"))

# change point color and shape
pchMy <- c("22","21","24","25","30")
colMy <- c("green", "red", "blue", "red", "black")
qplot(xMy, yMy, data = dfMy,
      col = colMy,
      pch = pchMy,
      main ="Using pchand col from Base Package (points size and shape changed)")
```
#Challenge Question 3
#Add title & rename legend & move legend to the left 
```{r echo = TRUE, fig=TRUE, fig.align='center'}
ggplot(mtcars, aes(disp, mpg, color=as.factor(cyl))) + 
    geom_point() + 
    geom_smooth(se=FALSE) + 
    ggtitle("mpg as function of disp") + 
    guides(color = guide_legend(title = "cylinder")) + 
    theme(legend.position = "left")
```


